name: flutter_clean_all
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/lamnhan066/flutter_clean_all

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutter_clean_all:
